name: Workflow for Cypress Tests (Manual, Push, Daily @ 8:00 pm)

on:
  push:
  #schedule:
  #- cron: '0 18 * * *'
  workflow_dispatch:
  
jobs:
  yarn-classic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
